apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gf1n6ytvw-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gf1n6ytvw-go 
  name: gf1n6ytvw-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gf1n6ytvw-go 
